"""Deterministic mock data for the CloudShadow frontend API."""

from typing import TypedDict


class CostSummary(TypedDict):
    currentCost: int
    previousCost: int
    percentageChange: float
    riskLevel: str
    performanceScore: int
    reliabilityScore: int


class CostTrendPoint(TypedDict):
    date: str
    cost: int


class Service(TypedDict):
    id: str
    name: str
    cost: int
    trafficChange: int
    cpuUsage: int
    latency: int
    status: str


COST_SUMMARY: CostSummary = {
    "currentCost": 742000,
    "previousCost": 536000,
    "percentageChange": 38.4,
    "riskLevel": "HIGH",
    "performanceScore": 82,
    "reliabilityScore": 94,
}

# Daily totals for the current incident window, in the same currency unit as
# the summary. The three dates follow the frozen frontend contract example.
COST_TREND: list[CostTrendPoint] = [
    {"date": "2026-09-20", "cost": 72000},
    {"date": "2026-09-21", "cost": 76000},
    {"date": "2026-09-22", "cost": 81000},
]

SERVICES: list[Service] = [
    {
        "id": "service-a",
        "name": "Service A",
        "cost": 180000,
        "trafficChange": 62,
        "cpuUsage": 71,
        "latency": 82,
        "status": "critical",
    },
    {
        "id": "service-b",
        "name": "Service B",
        "cost": 120000,
        "trafficChange": 48,
        "cpuUsage": 64,
        "latency": 76,
        "status": "warning",
    },
]

# Evidence describes observed or estimated changes. It supports a likely cause
# and does not claim that the dependency graph proves mathematical causality.
ROOT_CAUSE: dict[str, object] = {
    "title": "Unnecessary traffic generated by Service A",
    "confidence": 91,
    "impact": "HIGH",
    "chain": [
        {"event": "Service A traffic increased", "change": "+62%"},
        {"event": "Service B requests increased", "change": "+48%"},
        {"event": "Database queries increased", "change": "+37%"},
        {"event": "Compute usage increased", "change": "+31%"},
        {"event": "Network cost increased", "change": "+52%"},
    ],
    "evidence": [
        "Service A traffic increased by 62%",
        "Service B received 48% more requests",
        "Database queries increased by 37% alongside Service B request growth",
        "Compute usage increased by 31%",
        "Network cost increased by 52%",
        "Total cloud cost increased from 536000 to 742000 (38.4%)",
    ],
}

DEPENDENCIES: dict[str, list[dict[str, str]]] = {
    "nodes": [
        {"id": "api", "label": "API Gateway"},
        {"id": "service-a", "label": "Service A"},
        {"id": "service-b", "label": "Service B"},
        {"id": "database", "label": "Database"},
    ],
    "edges": [
        {"source": "api", "target": "service-a"},
        {"source": "service-a", "target": "service-b"},
        {"source": "service-b", "target": "database"},
    ],
}

RECOMMENDATIONS: list[dict[str, object]] = [
    {
        "title": "Enable caching for Service A",
        "estimatedSaving": 42000,
        "performanceImpact": "Positive",
        "reliabilityImpact": "Low Risk",
        "reason": "Repeated requests are increasing downstream traffic",
        "confidence": 88,
    }
]
