export const cloudAnalysis = {
  overview: {
    currentCost: 742000,
    previousCost: 536000,
    overallChange: 38.4,

    networkCost: 214000,
    networkChange: 52,

    computeCost: 186000,
    computeChange: 31,
  },

  services: [
    {
      id: "service-a",
      name: "Service A",
      category: "Compute",
      current: 180000,
      previous: 137000,
      change: 31,
      traffic: 62,
      cpu: 71,
      latency: "82 ms",
      status: "Critical",
      width: 78,
      impact: "HIGH",
      reason:
        "Traffic increased sharply and generated more downstream requests.",
      signal: "Primary billing signal",
      description:
        "Traffic growth is increasing downstream requests and compute usage.",
    },

    {
      id: "service-b",
      name: "Service B",
      category: "Network",
      current: 142000,
      previous: 93000,
      change: 52,
      traffic: 48,
      cpu: 64,
      latency: "76 ms",
      status: "Warning",
      width: 64,
      impact: "HIGH",
      reason:
        "Higher upstream traffic increased service-to-service network usage.",
      signal: "Downstream signal",
      description:
        "Higher upstream traffic is increasing service-to-service network usage.",
    },

    {
      id: "database",
      name: "Database",
      category: "Database",
      current: 124000,
      previous: 105000,
      change: 18,
      traffic: 18,
      cpu: 58,
      latency: "64 ms",
      status: "Healthy",
      width: 55,
      impact: "MEDIUM",
      reason:
        "Database activity increased as downstream request volume increased.",
      signal: "Normal activity",
      description:
        "Database activity increased moderately with application traffic.",
    },

    {
      id: "api-gateway",
      name: "API Gateway",
      category: "Network",
      current: 96000,
      previous: 72000,
      change: 33,
      traffic: 33,
      cpu: 42,
      latency: "51 ms",
      status: "Healthy",
      width: 43,
      impact: "MEDIUM",
      reason:
        "Additional incoming requests are contributing to gateway spending.",
      signal: "Normal activity",
      description:
        "Request volume increased with application activity.",
    },
  ],

  categories: [
    {
      name: "Network",
      cost: 214000,
      percentage: 29,
      color: "bg-teal-500",
    },
    {
      name: "Compute",
      cost: 186000,
      percentage: 25,
      color: "bg-blue-500",
    },
    {
      name: "Database",
      cost: 124000,
      percentage: 17,
      color: "bg-violet-500",
    },
    {
      name: "Storage",
      cost: 98000,
      percentage: 13,
      color: "bg-amber-500",
    },
  ],

  trend: [
    { date: "Sep 20", value: 45, cost: 36900 },
    { date: "Sep 21", value: 52, cost: 42600 },
    { date: "Sep 22", value: 58, cost: 47600 },
    { date: "Sep 23", value: 63, cost: 51700 },
    { date: "Sep 24", value: 70, cost: 57400 },
    { date: "Sep 25", value: 82, cost: 67200 },
    { date: "Sep 26", value: 96, cost: 78700 },
  ],

  rootCause: {
    title: "Unnecessary traffic generated by Service A",
    confidence: 91,
    impact: "HIGH",
  },

  chain: [
    {
      step: "01",
      serviceId: "service-a",
      title: "Service A traffic increased",
      change: "+62%",
      description:
        "Service A received significantly more traffic than the previous period.",
    },
    {
      step: "02",
      serviceId: "service-b",
      title: "Service B requests increased",
      change: "+48%",
      description:
        "Higher traffic from Service A generated additional downstream requests.",
    },
    {
      step: "03",
      serviceId: "compute",
      title: "Compute usage increased",
      change: "+31%",
      description:
        "The increased request volume required additional compute resources.",
    },
    {
      step: "04",
      serviceId: "network",
      title: "Network cost increased",
      change: "+52%",
      description:
        "Additional service-to-service traffic increased network spending.",
    },
  ],

  evidence: [
    "Service A traffic increased by 62%",
    "Service B received 48% more requests",
    "Compute usage increased by 31%",
    "Network cost increased by 52%",
  ],

  costImpact: {
    network: 52,
    compute: 31,
    serviceTraffic: 62,
  },

  dependencies: {
    nodes: [
      {
        id: "api",
        label: "API Gateway",
        description: "Entry point",
      },
      {
        id: "service-a",
        label: "Service A",
        description: "Traffic +62%",
      },
      {
        id: "service-b",
        label: "Service B",
        description: "Requests +48%",
      },
      {
        id: "database",
        label: "Database",
        description: "Data layer",
      },
    ],

    edges: [
      {
        id: "api-service-a",
        source: "api",
        target: "service-a",
      },
      {
        id: "service-a-service-b",
        source: "service-a",
        target: "service-b",
      },
      {
        id: "service-b-database",
        source: "service-b",
        target: "database",
      },
    ],
  },

  recommendations: [
    {
      id: "01",
      title: "Enable caching for Service A",
      saving: 42000,
      priority: "HIGH",
      confidence: 88,
      performance: "Positive",
      reliability: "Low Risk",
      reason:
        "Service A is generating repeated downstream requests. Caching can reduce unnecessary traffic and lower network and compute usage.",
      impact: "Reduce repeated requests",
    },
    {
      id: "02",
      title: "Optimize Service B requests",
      saving: 24000,
      priority: "MEDIUM",
      confidence: 82,
      performance: "Positive",
      reliability: "Low Risk",
      reason:
        "Service B is receiving significantly more requests because of upstream traffic from Service A.",
      impact: "Reduce downstream compute",
    },
    {
      id: "03",
      title: "Review network traffic between services",
      saving: 18000,
      priority: "MEDIUM",
      confidence: 79,
      performance: "Neutral",
      reliability: "Low Risk",
      reason:
        "Service-to-service communication is contributing significantly to network spending.",
      impact: "Reduce network transfer",
    },
  ],
};

export const formatINR = (value: number) =>
  `₹${value.toLocaleString("en-IN")}`;

export const formatLakhs = (value: number) =>
  `₹${(value / 100000).toFixed(2)}L`;